### ISSUE TITLE
Consider changing the repository layout

### ISSUE THREAD

**Issue by mjohnson9** [scotch/aego#3]
I'd like to suggest that you consider changing the repository layout to something similar to [Gorilla](https://github.com/gorilla)'s. Currently it results in long import paths and a moderately confusing structure.

Of course, it would be a good idea to maintain this repository for some time for backwards compatibility.

**Comment by kylefinley** [comment]
I do like Gorilla's approach -- the only question I have is how to do versioning. Currently I have:

```
aego/
  v1/
     pkg1/
     pkg2/
```

So when importing you get:

``` go
import "github.com/scotch/aego/v1/pkg1"

doSomeThingWith := pkg1.Something()
```

If I separated the package into there own repo's I could do something this

```
pkg1/
  v1/
pkg2/
  v1/
```

but when you import the package it would have to add a namespace E.g.

``` go
import pkg1 "github.com/scotch/pkg1/v1"

doSomeThingWith := pkg1.Something()
```

I guess I could add a directory inside of the `'v1'`:

```
pkg1/
  v1/
    pkg1/
pkg2/
  v1/
    pkg2/
```

Do you have any other suggestions? What do you think the best approach would be?

**Comment by mjohnson9** [comment]
I'm not too certain that I understand the reasoning behind the versioning, so I'm afraid I don't have any suggestions.

I've never thought of versioning to be needed for Go packages because they don't update automatically (especially in App Engine.) If the user is using Git submodules, you could use Git tags for each version so that they can choose which version to use or the user can choose a commit.

**Comment by kylefinley** [comment]
Thank you for the suggestions. I'll make the switch this weekend.

**Comment by kylefinley** [comment]
Ok I've created an organization called [gaego](https://github.com/gaego) (aego was taken) and I moved all of the aego packages to that location. I have granted your account push rights, so if you discovery any places were the code can be optimized please feel free to push directly to the repository. For any larger issues or changes please still create an issue so that we can discuss it -- I'll do the same. Please let me know if you have an issues.
